name: fp02
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - matplotlib
  - numpy
  - pandas
  - pytest
  - pywavelets
  - attrs
  - sphinx_rtd_theme
  - pip
  - pip:
    - fluxpart=0.2.*
