{% set name = "fluxpart" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluxpart-{{ version }}.tar.gz
  sha256: 63e2e6662316a0e5b3178c3252659a30618613746b8fbb3c6e7aa54bbf1accef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - pandas
    - pywavelets
    - attrs

test:
  imports:
    - fluxpart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  summary: Module for partitioning eddy covariance flux measurements.
  license: SAX-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thskaggs
